---
- hosts: pau
  gather_facts: yes
  become: yes
  tasks:
    - name: attempt to install kernel support packages for current version
      apt:
        name: "{{ item }}"
      with_items:
        - "build-essential"
        - "gcc"
        - "make"
